spring:
  profiles:
    active: prod
  application:
    name: gcc-fns  # 应用名

#--------------------------------------------
# 邮箱相关配置
#--------------------------------------------
  mail:
    host: smtp.sina.cn
    port: 465                     # 端口号
    username: zhi_oss@sina.cn     # 用户名
    password: cf0e9b95e4e43023    # 秘钥
    protocol: smtps               # 发送的协议
    properties:
      mail.smtp.ssl.enable: true  # 使用ssl安全连接

  servlet:
    multipart:
      max-file-size: 2MB          # 最大上传文件大小
      max-request-size: 2MB       # 最大请求大小


#--------------------------------------------
# mybatis相关配置
#--------------------------------------------
mybatis-plus:
  type-aliases-package: com.gcc.fns.model        # 别名
  mapper-locations: classpath:mapper/*.xml      # mapper存放位置


#--------------------------------------------
# 自定义配置
#--------------------------------------------
custom:
  jwt:
    subject: GCC-FNS          # 主体名
    secret: 2d#g24            # 秘钥
    expiration: 7         # 过期时间（天数）

  upload:
    count: 3                  # 用户文件上传最大次数

server:
  tomcat:
    max-swallow-size: -1     # 最大吞吐，-1为不限制

