server:
  port: 8888

spring:
  datasource:
    username: root
    password: Aliyun@qq.com
    url: jdbc:mysql://120.24.226.87:3306/gcc-fns?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSsl=false
    driver-class-name: com.mysql.cj.jdbc.Driver

    druid:
      initial-size: 5               # 初始数
      max-active: 10                # 最大活动数
      filters: stat,wall            # 底层开启功能，stat（sql监控），wall（防火墙）

      stat-view-servlet:            # 配置监控页功能
        login-username: admin
        login-password: admin
        url-pattern: /druid/*
        enabled: true

      web-stat-filter:      # 监控web
        enabled: true
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        url-pattern: /*

      filter:
        stat:                     # 对上面filters里面的stat的详细配置
          slow-sql-millis: 1000   # 慢sql为1000ms
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false


  redis:
    database: 3
    host: 120.24.226.87
    port: 6379
    password: redis888***

# dev环境下开启日志
mybatis-plus:
  configuration:
    log-impl: ""   # prod环境下关闭日志

logging:
  file:
    path: ./log         # 设置日志文件存放位置
  level:
    com.gcc.fns: info  # 设置对应的包的日志等级